### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by epos-eu** [epos-eu/WebApi#2]
@rrabissoni @andrejsim suggest to "dump" the most relevant  documentation we have in this repository, so BGS can work independently on the user interface.

I propose to include:
- updated version of Chris document
- sequence diagram (img and some standard UML format)

Whats your view?

**Comment by rrabissoni** [comment]
Why not!
as soon as possible i will upload it

**Comment by rrabissoni** [comment]
here they are :)
